# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Thirdone.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Third(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1470, 836)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(430, 60, 691, 51))
        self.label.setObjectName("label")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(100, 200, 711, 531))
        self.graphicsView.setObjectName("graphicsView")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(990, 410, 113, 32))
        self.pushButton.setObjectName("pushButton")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(990, 350, 104, 26))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(900, 350, 60, 16))
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(990, 480, 113, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1470, 36))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">Average Loan Amount by Month and Year</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Load"))
        self.comboBox.setItemText(0, _translate("MainWindow", "2000"))
        self.comboBox.setItemText(1, _translate("MainWindow", "2001"))
        self.comboBox.setItemText(2, _translate("MainWindow", "2002"))
        self.comboBox.setItemText(3, _translate("MainWindow", "2003"))
        self.comboBox.setItemText(4, _translate("MainWindow", "2004"))
        self.comboBox.setItemText(5, _translate("MainWindow", "2005"))
        self.comboBox.setItemText(6, _translate("MainWindow", "2006"))
        self.comboBox.setItemText(7, _translate("MainWindow", "2007"))
        self.comboBox.setItemText(8, _translate("MainWindow", "2008"))
        self.comboBox.setItemText(9, _translate("MainWindow", "2009"))
        self.comboBox.setItemText(10, _translate("MainWindow", "2010"))
        self.comboBox.setItemText(11, _translate("MainWindow", "2011"))
        self.comboBox.setItemText(12, _translate("MainWindow", "2012"))
        self.comboBox.setItemText(13, _translate("MainWindow", "2013"))
        self.comboBox.setItemText(14, _translate("MainWindow", "2014"))
        self.comboBox.setItemText(15, _translate("MainWindow", "2015"))
        self.label_2.setText(_translate("MainWindow", "year"))
        self.pushButton_2.setText(_translate("MainWindow", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Third()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
